### PR TITLE
Update Section2.2_Data.md

### PR DESCRIPTION
**Pull request by TWendl**
2.2.3 Clinical data (with tab) changed to 2.2.3 Clinical data (with space)

### CODE REVIEW

**Comment by TWendl** [comment]
Addresses issue "Corrections to Erythromycin Evaluation Report #6"

**Comment by sfrechen** [comment]
@Yuri05

**Comment by Yuri05** [comment]
@TWendl @sfrechen It's not ready to merge, right? Because the problems in #6 are not fixed.

**Comment by sfrechen** [comment]
ready to merge.
fixes #6

**Pull request merged**
